name: Frontend CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  build-and-deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'pnpm'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      id: pnpm-install
      with:
        version: 8
        run_install: true
        
    - name: Get pnpm store directory
      shell: bash
      run: |
        echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV
        
    - name: Add pnpm to PATH
      run: |
        echo "${{ env.HOME }}/.local/share/pnpm" >> $GITHUB_PATH

    - name: Install dependencies
      working-directory: ./frontend
      run: pnpm install --frozen-lockfile

    - name: Run linting
      working-directory: ./frontend
      run: pnpm lint

    - name: Run tests
      working-directory: ./frontend
      run: pnpm test --watchAll=false

    - name: Build for production
      working-directory: ./frontend
      run: pnpm build
      env:
        NODE_ENV: production
        VITE_API_URL: ${{ secrets.VITE_API_URL || 'https://v-b3.onrender.com/api' }}

    - name: Deploy to Vercel
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./frontend
        vercel-args: '--prod'
